### ISSUE TITLE
Error Rendering in childs

### ISSUE THREAD

**Issue by smkplus** [keijiro/HdrpVatExample#7] opened 2020-01-24 07:24 UTC
Hi i'm trying to export pyrofx vertex animation

https://github.com/smkplus/HoudiniPractice/wiki/Toon-Explosion

![Toon Explosion 1](https://user-images.githubusercontent.com/16706911/71239698-6fcd3f80-231c-11ea-96aa-cd5c5e246c90.gif)

But I have strange error!

![image](https://user-images.githubusercontent.com/16706911/73051411-eddeb200-3e97-11ea-8228-2ef2ad48e1c1.png)

![image](https://user-images.githubusercontent.com/16706911/73051565-2b433f80-3e98-11ea-9392-ad2c9441a32e.png)

**Comment by keijiro** [comment] 2020-01-24 07:42
Hmm, I have no idea. Please understand that I'm not a specialist of Houdini. I can solve issues in Unity's side, but I can't be very helpful about what's happening in Houdini's side. I'd recommend posting this to Issues of the SideFX Labs repository.

**Comment by keijiro** [comment] 2020-01-24 07:43
I'm closing this issue as the problem is in the exporter (SideFX Labs) side.

**Closed as completed** 2020-01-24 07:42 UTC
Labels: question

**Comment by smkplus** [comment] 2020-01-24 09:00
ok thank you anyway
I will ask this question in houdini forums
